### ISSUE TITLE
Admin UI

### ISSUE THREAD

**Issue by roscopecoltran** [ghetzel/pivot#3]
Hey Gary,

Hope you are all well !

I was wondering how complicated it would be to integrate your project with qor admin (https://github.com/qor/admin). It would be awesome to browse or edit data collections.

Also, there is another alternative, more entity and collection based, using admin-on-rest as a front-end, that I was thinking about. 

**Useful references:**
https://github.com/roscopecoltran/easyadmin
https://github.com/roscopecoltran/easyadmin/blob/docker-alpine/screenshots/architecture.png

My last question is about using a yaml configuration file to define several collections/schemas/entities per backend. I saw that you drafted some yaml configuration files, is it something that you intend to implement later ?

**Useful references:**
- https://github.com/yuya-takeyama/db2yaml

Ps. I could not make work the pivot web ui on a mysql database.

Cheers,
Richard

**Comment by ghetzel** [comment]
Sorry for the delay in getting back to you, my Github notification game is pretty weak atm and I didn't see this.  I'll review and reply, but I just wanted to let you know that I saw this.
